server:
  port: 8000
spring:
  application:
    name: tranh
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    default-property-inclusion: non_null
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  datasource:
    hikari:
      max-lifetime: 580000
    url: jdbc:mysql://localhost:3306/tranh?characterEncoding=utf8
    username: root
    password: CaoVanLam!542000
  mail:
    host: smtp.gmail.com
    port: 587
    username: sangdoannguyen7@gmail.com
    password: pgtobdwhogrbxvhl
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true