//2.
export const LOGIN = "LOGIN";
export const QUEN_MAT_KHAU = "QUEN_MAT_KHAU";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const SET_ERRORS = "SET_ERRORS";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_PROMOTION = "ADD_PROMOTION";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_PRICE = "ADD_PRODUCT_PRICE";
export const GET_ALL_CATEGOIES = "GET_ALL_CATEGOIES";
export const GET_ALL_PROMOTION = "GET_ALL_PROMOTION";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_PRICE = "GET_ALL_PRODUCT_PRICE";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_USER = "UPDATE_USER_BY_ADMIN";

export const UPDATE_PROMOTION = "UPDATE_PROMOTION";
export const UPDATE_PRODUCT_PRICE = "UPDATE_PRODUCT_PRICE";
export const UPDATE_ORDER_STATUS = "UPDATE_ORDER_STATUS";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_USERS = "GET_USERS";
export const GET_ORDERS = "GET_ORDERS";
export const GET_INVENTORY = "GET_INVENTORY";
export const UPDATE_INVENTORY = "UPDATE_INVENTORY";

export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PROMOTION = "DELETE_PROMOTION";
